#!/usr/bin/env bash
# This script installs Nginx and configures a custom HTTP response header X-Served-By with the server hostname

# Update and install nginx
apt-get update
apt-get install -y nginx

# Set hostname as required (OPTIONAL – only if not already set)
# Replace 6586-web-01 or 6586-web-02 with your specific hostname
# hostnamectl set-hostname 6586-web-01

# Add custom header in Nginx default config
sed -i '/^\s*location \/ {/a \        add_header X-Served-By \"$hostname\";' /etc/nginx/sites-available/default

# Restart Nginx
systemctl restart nginx

